



--
CREATE OR REPLACE TABLE PROFIT_TABLE (
    MID INT,
    MONTH_NAME VARCHAR(10),
    AMOUNT INT
);


INSERT INTO PROFIT_TABLE (MID, MONTH_NAME, AMOUNT) VALUES
(1, 'jan', 20000),
(2, 'feb', 10000),
(3, 'MAR', 40000),
(4, 'aprl', 50000),
(5, 'may', 30000),
(6, 'jun', 70000),
(7, 'july', 80000),
(8, 'aug', 5000),
(9, 'sep', 100000),
(10, 'oct', 110000),
(11, 'nov', 120000),
(12, 'dec', 60000);


SELECT 
    MID,
    MONTH_NAME,
    AMOUNT,
    CASE 
        WHEN LAG(AMOUNT) OVER (ORDER BY MID) IS NULL THEN 'NA'
        ELSE CAST(AMOUNT - LAG(AMOUNT) OVER (ORDER BY MID) AS VARCHAR)
    END AS PROFIT_LOSS,
    CASE 
        WHEN LAG(AMOUNT) OVER (ORDER BY MID) IS NULL THEN 'NA'
        WHEN AMOUNT - LAG(AMOUNT) OVER (ORDER BY MID) > 0 THEN 'PROFIT'
        WHEN AMOUNT - LAG(AMOUNT) OVER (ORDER BY MID) < 0 THEN 'LOSS'
        ELSE 'NO CHANGE'
    END AS STATUS
FROM PROFIT_TABLE
ORDER BY MID;